# Make sure to check the documentation at http://goreleaser.com
project_name: gab
before:
  hooks:
    - go mod tidy
builds:
  - id: gab
    main: ./cli/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
    - LICENSE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    # GitHub/GitLab repository to push the formula to
    # Gitea is not supported yet, but the support coming
    tap:
      owner: abtris
      name: homebrew-tap
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Ladislav Prskavec
      email: ladislav@prskavec.net

    # Default is empty.
    license: "MIT"
    homepage: "https://github.com/abtris/ga-badge"
    description: "Github Action Badge Generator"
