# Make sure to check the documentation at http://goreleaser.com
project_name: gab
before:
  hooks:
    - go mod tidy
builds:
  - id: gab
    main: ./cli/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.BuildDate={{.Date}}
      - -X main.CommitHash={{ .ShortCommit }}
      - -X main.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
    - LICENSE
    - README.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
brews:
  -
    # GitHub homebrew repository created by `brew tap-new` command  first!
    # brew tap-new will create git repo and that can be issue and try commit and
    # you use `useconfigonly = true` settings in `~/.gitconfig`
    # use brew tap-new --no-git to prevent issue and after you set owner you init and push manually.
    tap:
      owner: abtris
      name: homebrew-tap
    # Git author used to commit to the repository.
    commit_author:
      name: Ladislav Prskavec
      email: ladislav@prskavec.net

    # homebrew mandatory fields (not mandatory for goreleaser)
    license: "MIT"
    homepage: "https://github.com/abtris/ga-badge"
    description: "Github Action Badge Generator"
